### ISSUE TITLE
Alternate address list location

### ISSUE THREAD

**Issue by sparr** [iDestyKK/GMS_AudioGroup_Extract#1]
The offsets to every file are stored in the header, between what you're using as the first size offset and the location it points to. This could be used as an alternate method for iterating through the file, or as a way to check that the existing method is producing the expected results.

**Comment by iDestyKK** [comment]
I like your way. Rearranged the code and set a release as [v1.0.0](https://github.com/iDestyKK/GMS_AudioGroup_Extract/releases/tag/v1.0.0). Thanks!
